from openbabel import openbabel as ob


from molecular_qm_models import Molecule
import logging
logger = logging.getLogger(__name__)

def compute_iupac_name(molecule: Molecule) -> str:
    """
    Computes the IUPAC name using Open Babel, with a fallback if the 
    'name' format plugin is missing.
    """
    if not molecule.atoms:
        raise ValueError("Cannot compute IUPAC name for empty molecule")

    # 1. Convert SimStack Molecule to XYZ string
    xyz_lines = [str(len(molecule.atoms)), "Generated by SimStack"]
    for atom in molecule.atoms:
        xyz_lines.append(f"{atom.element} {atom.x} {atom.y} {atom.z}")
    xyz_str = "\n".join(xyz_lines)

    try:
        # 2. Read XYZ into an Open Babel molecule
        conversion = ob.OBConversion()
        if not conversion.SetInAndOutFormats("xyz", "smi"):
            raise RuntimeError("Open Babel does not support XYZ to SMILES conversion")

        ob_mol = ob.OBMol()
        if not conversion.ReadString(ob_mol, xyz_str):
            raise RuntimeError("Open Babel failed to read molecule from XYZ string")

        # 3. Generate SMILES
        smiles_output = conversion.WriteString(ob_mol).strip()
        if not smiles_output:
            raise RuntimeError("Open Babel failed to generate SMILES")

        smiles = smiles_output.split()[0]

        # 4. Use PubChemPy to resolve IUPAC name
        try:
            import pubchempy as pcp

            compounds = pcp.get_compounds(smiles, namespace="smiles")
            if compounds and compounds[0].iupac_name:
                return compounds[0].iupac_name
        except Exception as pubchem_error:
            logger.warning("Could not resolve IUPAC name from PubChem: %s", pubchem_error)

        # Ultimate fallback
        formula = ob_mol.GetFormula()
        if formula:
            return formula

        return smiles

    except Exception as e:
        logger.error(f"Error computing IUPAC name for {molecule.name}: {e}")
        raise e
