from openbabel import pybel
from molecular_qm_models import Molecule

def compute_smiles(molecule: Molecule) -> str:
    """
    Compute the canonical SMILES string for a molecule using Open Babel.
    """
    if not molecule.atoms:
        raise ValueError("Cannot compute SMILES for empty molecule")

    # Create XYZ string from Molecule object
    xyz_lines = [str(len(molecule.atoms)), "Generated by SimStack"]
    for atom in molecule.atoms:
        xyz_lines.append(f"{atom.element} {atom.x} {atom.y} {atom.z}")
    
    xyz_str = "\n".join(xyz_lines)

    try:
        # Read from XYZ and write to SMILES (canonical by default in pybel)
        mol = pybel.readstring("xyz", xyz_str)
        # "smi" format in Open Babel 2.3 produces canonical SMILES
        smiles = mol.write("smi").split()[0]
        return smiles
    except Exception as e:
        raise ValueError(f"Open Babel failed to compute SMILES: {e}")

