try:
    from openbabel import pybel
except ImportError:
    import pybel

from molecular_qm_models import Molecule
import logging
logger = logging.getLogger(__name__)

def compute_iupac_name(molecule: Molecule) -> str:
    """
    Computes the IUPAC name using Open Babel, with a fallback if the 
    'name' format plugin is missing.
    """
    if not molecule.atoms:
        raise ValueError("Cannot compute IUPAC name for empty molecule")

    # 1. Convert SimStack Molecule to XYZ string
    xyz_lines = [str(len(molecule.atoms)), "Generated by SimStack"]
    for atom in molecule.atoms:
        xyz_lines.append(f"{atom.element} {atom.x} {atom.y} {atom.z}")
    xyz_str = "\n".join(xyz_lines)

    try:
        # 2. Read into pybel
        mol = pybel.readstring("xyz", xyz_str)
        
        # 3. Check if the 'name' format is supported by this OB installation
        if "name" in pybel.outformats:
            name = mol.write("name").strip()
            if name:
                return name

        # 4. Fallback: If 'name' is missing, generate SMILES and use PubChemPy
        # (This leverages the fact that you already have pubchempy in your project)
        import pubchempy as pcp
        smiles = mol.write("smi").split()[0]
        compounds = pcp.get_compounds(smiles, namespace='smiles')
        
        if compounds is not None and compounds[0].iupac_name:
            return compounds[0].iupac_name
            
        return mol.formula # Ultimate fallback

    except Exception as e:
        logger.error(f"Error computing IUPAC name for {molecule.name}: {e}")
        raise e
