import pytest

from molecular_qm_models import Atom, Molecule, MoleculeList

from molecular_qm_util.rdkit_scripts.rdkit_conformers import (
    generate_rdkit_conformers,
    generate_rdkit_conformers_from_smiles,
    _rdkit_conf_to_molecule,
    _require_rdkit,
    _write_xyz_from_rdkit,
)
from molecular_qm_util.rdkit_scripts.smiles_to_molecule import smiles_to_molecule

# Ethanol (CCO) has 2 C + 6 H + 1 O = 9 atoms once hydrogens are added.
_ETHANOL_SMILES = "CCO"
_ETHANOL_NUM_ATOMS = 9


def _assert_ranked_molecule_list(conformers, expected_atoms):
    """Common assertions for the ``MoleculeList`` returned by the generators."""
    assert isinstance(conformers, MoleculeList)
    assert len(conformers) >= 1

    energies = []
    for molecule in conformers:
        assert isinstance(molecule, Molecule)
        assert len(molecule.atoms) == expected_atoms
        # Each conformer carries its force-field energy and an energy ranking.
        assert "energy" in molecule.properties
        assert isinstance(molecule.properties["energy"], float)
        assert "rank_id" in molecule.properties
        energies.append(molecule.properties["energy"])

    # ``prune_conformers`` assigns rank_id as a contiguous 0..n-1 range.
    rank_ids = [m.properties["rank_id"] for m in conformers]
    assert rank_ids == list(range(len(conformers)))

    # Conformers are returned energy-sorted (lowest energy first).
    assert energies == sorted(energies)


def test_require_rdkit_available():
    # RDKit is a hard dependency of this test suite, so this must not raise.
    _require_rdkit()


def test_generate_rdkit_conformers_returns_ranked_molecule_list():
    molecule = smiles_to_molecule(_ETHANOL_SMILES)
    molecule.smiles = _ETHANOL_SMILES

    conformers = generate_rdkit_conformers(molecule, num_confs=3, seed=1)

    _assert_ranked_molecule_list(conformers, _ETHANOL_NUM_ATOMS)


def test_generate_rdkit_conformers_from_smiles():
    conformers = generate_rdkit_conformers_from_smiles(
        _ETHANOL_SMILES, num_confs=3, seed=1
    )

    _assert_ranked_molecule_list(conformers, _ETHANOL_NUM_ATOMS)
    for molecule in conformers:
        assert molecule.smiles == _ETHANOL_SMILES


def test_generate_rdkit_conformers_invalid_smiles_raises():
    molecule = Molecule()
    molecule.smiles = "this_is_not_a_valid_smiles$$$"

    with pytest.raises(ValueError, match="Invalid SMILES"):
        generate_rdkit_conformers(molecule, num_confs=1)


def test_rdkit_conf_to_molecule_copies_geometry_and_energy():
    from rdkit import Chem
    from rdkit.Chem import AllChem

    mol = Chem.MolFromSmiles(_ETHANOL_SMILES)
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol, AllChem.ETKDG())
    conf = mol.GetConformer()

    molecule = _rdkit_conf_to_molecule(mol, conf, energy=-1.23, smiles=_ETHANOL_SMILES)

    assert isinstance(molecule, Molecule)
    assert molecule.smiles == _ETHANOL_SMILES
    assert molecule.properties["energy"] == -1.23
    assert len(molecule.atoms) == mol.GetNumAtoms()
    for atom in molecule.atoms:
        assert isinstance(atom, Atom)
        assert atom.element


def test_write_xyz_from_rdkit(tmp_path):
    from rdkit import Chem
    from rdkit.Chem import AllChem

    mol = Chem.MolFromSmiles(_ETHANOL_SMILES)
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol, AllChem.ETKDG())
    conf_id = mol.GetConformer().GetId()

    out_xyz = tmp_path / "conformer.xyz"
    _write_xyz_from_rdkit(mol, conf_id, out_xyz)

    lines = out_xyz.read_text(encoding="utf-8").splitlines()
    assert lines[0] == str(mol.GetNumAtoms())
    assert lines[1] == "generated by RDKit"
    # header (2 lines) + one line per atom
    assert len(lines) == mol.GetNumAtoms() + 2
    for line in lines[2:]:
        parts = line.split()
        assert len(parts) == 4  # element + x + y + z
        float(parts[1]), float(parts[2]), float(parts[3])
