from rdkit import Chem
from rdkit.Chem import rdDetermineBonds
from molecular_qm_models import Molecule


def molecule_to_smiles(molecule: Molecule) -> str:
    """
    Convert a Molecule object to a canonical SMILES string using RDKit.

    :param molecule: A Molecule object containing atoms with 3D coordinates.
    :return: Canonical SMILES string.
    :raises ValueError: If the molecule is empty or conversion fails.
    """
    if molecule is None or not getattr(molecule, "atoms", None) or len(molecule.atoms) == 0:
        raise ValueError("Cannot compute SMILES for empty molecule")

    xyz_lines = [str(len(molecule.atoms)), "Generated by molecular_qm_util"]
    for atom in molecule.atoms:
        element = getattr(atom, "element", None) or getattr(atom, "species", None)
        if not element or not str(element).strip():
            raise ValueError(f"Invalid atom without element symbol: {atom}")
        element = str(element).strip()
        x = float(getattr(atom, "x", 0.0))
        y = float(getattr(atom, "y", 0.0))
        z = float(getattr(atom, "z", 0.0))
        xyz_lines.append(f"{element:3s} {x:.8f} {y:.8f} {z:.8f}")

    xyz_str = "\n".join(xyz_lines)

    charge = getattr(molecule, "charge", None)
    if charge is None and hasattr(molecule, "properties") and isinstance(molecule.properties, dict):
        charge = molecule.properties.get("charge", None)
    if charge is not None:
        try:
            charge = int(charge)
        except Exception:
            charge = 0
    else:
        charge = 0

    rd_mol = Chem.MolFromXYZBlock(xyz_str)
    if rd_mol is None:
        raise ValueError("RDKit failed to parse molecule coordinates from XYZ block")

    # Determine bonds and connectivity
    bonds_determined = False
    for use_hueckel in [False, True]:
        if bonds_determined:
            break
        for cov_factor in [1.3, 1.4, 1.2]:
            try:
                mol_copy = Chem.Mol(rd_mol)
                rdDetermineBonds.DetermineBonds(
                    mol_copy,
                    useHueckel=use_hueckel,
                    charge=charge,
                    covFactor=cov_factor,
                    allowChargedFragments=True,
                    embedChiral=True,
                )
                rd_mol = mol_copy
                bonds_determined = True
                break
            except Exception:
                continue

    if not bonds_determined:
        try:
            mol_copy = Chem.Mol(rd_mol)
            rdDetermineBonds.DetermineConnectivity(mol_copy, charge=charge)
            rdDetermineBonds.DetermineBondOrders(
                mol_copy, charge=charge, allowChargedFragments=True, embedChiral=True
            )
            rd_mol = mol_copy
            bonds_determined = True
        except Exception:
            pass

    if not bonds_determined:
        try:
            mol_copy = Chem.Mol(rd_mol)
            rdDetermineBonds.DetermineConnectivity(mol_copy, charge=charge)
            rd_mol = mol_copy
            bonds_determined = True
        except Exception as e:
            raise ValueError(f"Failed to determine molecular bonds using RDKit: {e}")

    try:
        rd_mol_no_h = Chem.RemoveHs(rd_mol)
    except Exception:
        rd_mol_no_h = rd_mol

    return Chem.MolToSmiles(rd_mol_no_h, canonical=True)


compute_smiles = molecule_to_smiles
molecule_to_canonical_smiles = molecule_to_smiles
