from __future__ import annotations
import copy
from enum import Enum
from typing import Optional, Union

from molecular_qm_models import Atom, Molecule
from simstack.core.node import node


class RDKitForceField(str, Enum):
    """Supported RDKit force fields for molecular optimization."""
    MMFF94 = "mmff94"
    MMFF94S = "mmff94s"
    UFF = "uff"


try:
    from rdkit import Chem
    from rdkit.Chem import AllChem, rdDetermineBonds
except ImportError as e:
    Chem = None
    AllChem = None
    rdDetermineBonds = None
    _RDKIT_IMPORT_ERROR = e
else:
    _RDKIT_IMPORT_ERROR = None

try:
    from openbabel import pybel
except ImportError:
    pybel = None


def _require_rdkit() -> None:
    if Chem is None or AllChem is None:
        raise RuntimeError("RDKit is required for molecule optimization.") from _RDKIT_IMPORT_ERROR


def molecule_to_rdkit(molecule: Molecule) -> Chem.Mol:
    """
    Convert a Molecule object into an RDKit Mol with 3D coordinates.
    """
    _require_rdkit()

    if molecule is None or not getattr(molecule, "atoms", None) or len(molecule.atoms) == 0:
        raise ValueError("Cannot convert empty molecule to RDKit")

    lines = [str(len(molecule.atoms)), molecule.smiles or ""]
    for atom in molecule.atoms:
        element = getattr(atom, "element", None) or getattr(atom, "species", None) or "C"
        element = str(element).strip()
        lines.append(f"{element} {atom.x:.10f} {atom.y:.10f} {atom.z:.10f}")
    xyz = "\n".join(lines) + "\n"

    # 1. Try OpenBabel if available
    if pybel is not None:
        try:
            ob_mol = pybel.readstring("xyz", xyz)
            ob_mol_sdf = ob_mol.write("sdf")
            mol = Chem.MolFromMolBlock(ob_mol_sdf, removeHs=False)
            if mol is not None:
                return mol
        except Exception:
            pass

    # 2. Fallback: Parse XYZ block with RDKit and determine bonds
    xyz_lines = [str(len(molecule.atoms)), molecule.smiles or "Generated by molecular_qm_util"]
    for atom in molecule.atoms:
        element = getattr(atom, "element", None) or getattr(atom, "species", None) or "C"
        element = str(element).strip()
        xyz_lines.append(f"{element:3s} {atom.x:.8f} {atom.y:.8f} {atom.z:.8f}")
    xyz_str = "\n".join(xyz_lines)

    charge = 0
    if hasattr(molecule, "charge") and molecule.charge is not None:
        try:
            charge = int(molecule.charge)
        except Exception:
            charge = 0
    elif hasattr(molecule, "properties") and isinstance(molecule.properties, dict):
        charge = int(molecule.properties.get("charge", 0) or 0)

    rd_mol = Chem.MolFromXYZBlock(xyz_str)
    if rd_mol is not None and rdDetermineBonds is not None:
        bonds_determined = False
        for use_hueckel in [False, True]:
            if bonds_determined:
                break
            for cov_factor in [1.3, 1.4, 1.2]:
                try:
                    mol_copy = Chem.Mol(rd_mol)
                    rdDetermineBonds.DetermineBonds(
                        mol_copy,
                        useHueckel=use_hueckel,
                        charge=charge,
                        covFactor=cov_factor,
                        allowChargedFragments=True,
                        embedChiral=True,
                    )
                    rd_mol = mol_copy
                    bonds_determined = True
                    break
                except Exception:
                    continue
        if bonds_determined:
            return rd_mol

    if rd_mol is not None:
        return rd_mol

    raise RuntimeError("Failed to convert Molecule to RDKit Mol.")


def rdkit_to_molecule(rdkit_mol: Chem.Mol, conf_id: int = 0, energy: Optional[float] = None, smiles: Optional[str] = None) -> Molecule:
    """
    Convert a single conformer of an RDKit molecule into a Molecule.
    """
    conf = rdkit_mol.GetConformer(conf_id)
    mol = Molecule()
    mol.smiles = smiles
    for atom in rdkit_mol.GetAtoms():
        pos = conf.GetAtomPosition(atom.GetIdx())
        mol.add_atom(Atom(element=atom.GetSymbol(), x=pos.x, y=pos.y, z=pos.z))
    if energy is not None:
        mol.properties["energy"] = energy
    return mol


class RDKitParams:
    """
    Parameters for RDKit optimization.
    """
    max_iters: int = 500
    forcefield: Union[str, RDKitForceField] = RDKitForceField.MMFF94
    mmff_variant: str = "MMFF94"

@node
def rdkit_optimize(
    molecule: Molecule,
    params: RDKitParams, **kwargs
) -> Molecule:
    """
    Optimizes the 3D geometry of a molecular structure using RDKit force fields.

    This function uses RDKit's force field optimization to minimize the energy of
    a molecular structure. It supports the MMFF94, MMFF94s, and UFF force fields
    for geometry optimization. The optimized molecule is returned along with its
    energy and additional metadata.

    :param molecule: The molecule to be optimized. It can either be an instance of
        `Molecule` or `rdkit.Chem.Mol`. The molecular structure must have a valid
        3D geometry.
    :type molecule: Molecule or Chem.Mol
    :param params: The parameters for the RDKit optimization process, encapsulated
        in an `RDKitParams` object. These parameters include details such as
        force field variants and maximum iterations.
    :type params: RDKitParams
    :param kwargs: Additional keyword arguments for customizing the optimization
        process or passing supplementary information.
    :return: A new `Molecule` object representing the optimized structure. The
        returned molecule includes updated geometry, energy value, and method used
        for optimization.
    :rtype: Molecule
    :raises TypeError: If the provided molecular object is not an instance of
        `Molecule` or `rdkit.Chem.Mol`.
    :raises ValueError: If an unsupported force field is specified in the
        parameters.
    """
    _require_rdkit()

    forcefield = params.forcefield
    mmff_variant = params.mmff_variant

    if isinstance(molecule, Molecule):
        mol = molecule_to_rdkit(molecule)
        orig_smiles = molecule.smiles
        orig_props = copy.deepcopy(molecule.properties) if hasattr(molecule, "properties") and isinstance(molecule.properties, dict) else {}
    elif isinstance(molecule, Chem.Mol):
        mol = Chem.Mol(molecule)
        orig_smiles = mol.GetProp("_Name") if mol.HasProp("_Name") else None
        orig_props = {}
    else:
        raise TypeError(f"Unsupported molecule type: {type(molecule)}")

    ff_val = forcefield.value if isinstance(forcefield, Enum) else str(forcefield)
    ff_lower = ff_val.lower()

    if ff_lower in ("mmff", "mmff94", "mmff94s", "rdkit_mmff94"):
        variant = mmff_variant if mmff_variant else ("MMFF94s" if ff_lower == "mmff94s" else "MMFF94")
        if ff_lower == "mmff94s":
            variant = "MMFF94s"
        AllChem.MMFFOptimizeMolecule(mol, mmffVariant=variant, maxIters=max_iters)
        mp = AllChem.MMFFGetMoleculeProperties(mol, mmffVariant=variant)
        ff = AllChem.MMFFGetMoleculeForceField(mol, mp)
        method_name = f"rdkit+{ff_lower}"
    elif ff_lower in ("uff", "rdkit_uff"):
        AllChem.UFFOptimizeMolecule(mol, maxIters=max_iters)
        ff = AllChem.UFFGetMoleculeForceField(mol)
        method_name = "rdkit+uff"
    else:
        raise ValueError(
            f"Unsupported force field '{forcefield}'. Supported options are: {[f.value for f in RDKitForceField]}"
        )

    if ff is not None:
        ff.Initialize()
        energy = float(ff.CalcEnergy())
    else:
        energy = 0.0

    optimized_molecule = rdkit_to_molecule(mol, 0, energy=energy, smiles=orig_smiles)
    for k, v in orig_props.items():
        if k not in ("energy", "method"):
            optimized_molecule.properties[k] = v

    optimized_molecule.properties["energy"] = energy
    optimized_molecule.properties["method"] = method_name

    return optimized_molecule
