def add_hydrogen_to_molecule(molecule, charge=0, use_indigo_for_neutral=True):
    """
    Add hydrogen atoms to a molecule using Indigo or OpenBabel depending on charge.
    
    Args:
        molecule: Molecule object containing atoms
        charge: Molecular charge (default: 0)
        use_indigo_for_neutral: If True, use Indigo for neutral molecules, OpenBabel for charged
    
    Returns:
        Molecule: New molecule with hydrogen atoms added
    """
    try:
        # Import libraries
        from indigo import Indigo
        import openbabel as ob
        
        # Get charge from molecule properties if not provided
        if charge == 0 and hasattr(molecule, 'charge'):
            charge = molecule.charge
        
        # Choose library based on charge
        if charge == 0 and use_indigo_for_neutral:
            return _add_hydrogen_indigo(molecule)
        else:
            return _add_hydrogen_openbabel(molecule, charge)
            
    except ImportError as e:
        raise ImportError(f"Required library not found: {e}")
    except Exception as e:
        raise RuntimeError(f"Error adding hydrogens: {e}")


def _add_hydrogen_indigo(molecule):
    """Add hydrogens using Indigo."""
    from indigo import Indigo
    from molecular_qm_models import Molecule, Atom
    
    indigo = Indigo()
    
    # Create XYZ string from molecule to load into Indigo
    xyz_lines = [str(len(molecule.atoms)), "Generated by SimStack"]
    for atom in molecule.atoms:
        xyz_lines.append(f"{atom.element} {atom.x} {atom.y} {atom.z}")
    xyz_str = "\n".join(xyz_lines)
    
    # Load molecule from XYZ
    mol = indigo.loadMolecule(xyz_str)
    
    # Add hydrogens
    mol.addImplicitHydrogens()
    
    # Convert back to Molecule object
    new_molecule = Molecule()
    new_molecule.properties = molecule.properties.copy()
    new_molecule.smiles = molecule.smiles
    new_molecule.formula = molecule.formula
    
    for atom in mol.iterateAtoms():
        pos = atom.xyz()
        new_atom = Atom(
            element=atom.symbol(),
            x=pos[0],
            y=pos[1],
            z=pos[2]
        )
        new_molecule.add_atom(new_atom)
    
    return new_molecule




def _add_hydrogen_openbabel(molecule, charge=0):
    """
    Add hydrogen atoms using OpenBabel.
    
    Args:
        molecule: Molecule object
        charge: Molecular charge
    
    Returns:
        Molecule: New molecule with hydrogens added
    """
    import openbabel as ob
    from molecular_qm_models import Atom
    
    # Create OpenBabel molecule
    mol = ob.OBMol()
    
    # Add atoms to OpenBabel molecule
    for atom in molecule.atoms:
        ob_atom = mol.NewAtom()
        # Use SetAtomicNum instead of SetAtomicSymbol
        element_number = ob.GetAtomicNum(atom.element)
        ob_atom.SetAtomicNum(element_number)
        ob_atom.SetVector(atom.x, atom.y, atom.z)
    
    # Set charge
    mol.SetTotalCharge(charge)
    
    # Add hydrogens
    mol.AddHydrogens()
    
    # Convert back to our Atom objects
    new_atoms = []
    for i in range(mol.NumAtoms()):
        ob_atom = mol.GetAtom(i + 1)  # OpenBabel uses 1-based indexing
        element_symbol = ob.GetSymbol(ob_atom.GetAtomicNum())
        x, y, z = ob_atom.GetX(), ob_atom.GetY(), ob_atom.GetZ()
        new_atoms.append(Atom(element=element_symbol, x=x, y=y, z=z))
    
    # Create new molecule
    from molecular_qm_models import Molecule
    new_molecule = Molecule(atoms=new_atoms, properties=molecule.properties.copy())
    
    return new_molecule




def _openbabel_to_molecule(ob_mol, original_molecule):
    """Convert OpenBabel molecule back to Molecule object."""
    from molecular_qm_models import Molecule, Atom
    import openbabel as ob
    
    # Create new molecule
    new_molecule = Molecule()
    
    # Copy properties from original
    new_molecule.properties = original_molecule.properties.copy()
    new_molecule.smiles = original_molecule.smiles
    new_molecule.formula = original_molecule.formula
    
    # Add atoms from OpenBabel molecule
    for atom in ob.OBMolAtomIter(ob_mol):
        new_atom = Atom(
            element=atom.GetAtomicSymbol(),
            x=atom.GetX(),
            y=atom.GetY(),
            z=atom.GetZ()
        )
        new_molecule.add_atom(new_atom)
    
    return new_molecule