from indigo import Indigo
from molecular_qm_models import Molecule

import logging
logger = logging.getLogger(__name__)

def compute_smiles(molecule: Molecule) -> str:
    """
    Compute the canonical SMILES string for a molecule.

    :param molecule: A Molecule object containing atoms with 3D coordinates
    :return: Canonical SMILES string
    :raises ValueError: If the molecule cannot be converted to SMILES
    """
    if not molecule.atoms:
        raise ValueError("Cannot compute SMILES for empty molecule")

    try:
        indigo = Indigo()

        xyz_lines = [str(len(molecule.atoms)), "Generated by SimStack"]
        for atom in molecule.atoms:
            # Use strict float formatting to avoid scientific notation or None issues
            xyz_lines.append(f"{atom.element.strip():3s} {float(atom.x):.8f} {float(atom.y):.8f} {float(atom.z):.8f}")

        xyz_str = "\n".join(xyz_lines)

        # Load molecule from XYZ string
        # Indigo automatically perceives bonds from XYZ coordinates
        indigo_mol = indigo.loadMolecule(xyz_str)

        # Generate canonical SMILES
        smiles = indigo_mol.canonicalSmiles()

        return smiles

    except Exception as e:
        logger.error(f"Error computing SMILES: {e}")
        raise ValueError(f"Failed to compute SMILES: {e}")
